version: '3.9'

services:
  client-dashboard:
    build:
      context: ./client-dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server-dashboard
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - dashboard-network

  server-dashboard:
    build:
      context: ./server-dashboard
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your-super-secret-jwt-key-2024
      - JWT_EXPIRES_IN=24h
      - DYNAMODB_LOCAL_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=local
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
    depends_on:
      - dynamodb-local
    volumes:
      - ./server-dashboard/logs:/usr/src/app/logs
    networks:
      - dashboard-network

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    user: "1000:1000"  # Added user mapping
    command: "-jar DynamoDBLocal.jar -sharedDb"  # Removed dbPath
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge

volumes:
  dynamodb_data:  # Changed volume name to be more consistent
    driver: local